#This file defines all the categories you are using

spring:
  name: Spring
  description: Study about spring boot
database:
  name: database
  description: Study about database
#using-odin2: not finished
#  name: nginx
#  description: nginx
refactoring:
  name: refactoring
  description: Study about code refactoring
docker:
  name: docker
  description: Study about docker.