#This file defines all the categories you are using

spring:
  name: spring
  description: Study about spring boot
database:
  name: database
  description: Study about database
refactoring:
  name: refactoring
  description: Study about code refactoring
cicd:
  name: cicd
  description: Study Continuous Integrate and Continuous Deployment